"""Initial migration: Add all 8 database tables

Revision ID: f2c01374e0d5
Revises: 
Create Date: 2026-07-19 10:00:43.222447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f2c01374e0d5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schema_version')
    op.add_column('agent_deltas', sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Record last update timestamp'))
    op.alter_column('agent_deltas', 'story_bible_id',
               existing_type=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               type_=sa.String(length=36),
               comment='Story Bible ID',
               existing_nullable=False)
    op.alter_column('agent_deltas', 'agent_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment='Agent name',
               existing_nullable=False)
    op.alter_column('agent_deltas', 'execution_time_ms',
               existing_type=mysql.INTEGER(),
               comment='Agent execution time in milliseconds',
               existing_comment='Agent execution time',
               existing_nullable=True)
    op.alter_column('agent_deltas', 'cost',
               existing_type=mysql.DECIMAL(precision=10, scale=4),
               server_default=None,
               nullable=False,
               existing_comment='Cost in USD')
    op.alter_column('agent_deltas', 'id',
               existing_type=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               type_=sa.String(length=36),
               comment='UUID primary key',
               existing_comment='UUID',
               existing_nullable=False)
    op.alter_column('agent_deltas', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(),
               nullable=False,
               comment='Record creation timestamp')
    op.drop_index(op.f('idx_agent'), table_name='agent_deltas')
    op.drop_index(op.f('idx_created_at'), table_name='agent_deltas')
    op.drop_index(op.f('idx_story_bible'), table_name='agent_deltas')
    op.create_index(op.f('ix_agent_deltas_agent_name'), 'agent_deltas', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_deltas_story_bible_id'), 'agent_deltas', ['story_bible_id'], unique=False)
    op.drop_table_comment(
        'agent_deltas',
        existing_comment='Agent change audit trail',
        schema=None
    )
    op.add_column('api_costs', sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Record last update timestamp'))
    op.alter_column('api_costs', 'project_id',
               existing_type=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               type_=sa.String(length=36),
               comment='Project ID',
               existing_nullable=False)
    op.alter_column('api_costs', 'provider',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='AI provider (mistral, openai)',
               existing_comment='mistral, openai',
               existing_nullable=False)
    op.alter_column('api_costs', 'api_type',
               existing_type=mysql.ENUM('text', 'image', collation='utf8mb4_unicode_ci'),
               comment='API type',
               existing_nullable=False)
    op.alter_column('api_costs', 'success',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               nullable=False,
               comment='Whether request succeeded')
    op.alter_column('api_costs', 'error_message',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Error message if failed',
               existing_nullable=True)
    op.alter_column('api_costs', 'id',
               existing_type=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               type_=sa.String(length=36),
               comment='UUID primary key',
               existing_comment='UUID',
               existing_nullable=False)
    op.alter_column('api_costs', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(),
               nullable=False,
               comment='Record creation timestamp')
    op.drop_index(op.f('idx_api_type'), table_name='api_costs')
    op.drop_index(op.f('idx_created_at'), table_name='api_costs')
    op.drop_index(op.f('idx_project_provider'), table_name='api_costs')
    op.create_index(op.f('ix_api_costs_api_type'), 'api_costs', ['api_type'], unique=False)
    op.create_index(op.f('ix_api_costs_project_id'), 'api_costs', ['project_id'], unique=False)
    op.create_index(op.f('ix_api_costs_provider'), 'api_costs', ['provider'], unique=False)
    op.drop_table_comment(
        'api_costs',
        existing_comment='API usage and cost tracking',
        schema=None
    )
    op.alter_column('chapters', 'story_bible_id',
               existing_type=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               type_=sa.String(length=36),
               comment='Story Bible ID',
               existing_nullable=False)
    op.alter_column('chapters', 'chapter_number',
               existing_type=mysql.INTEGER(),
               comment='Chapter number (1-based)',
               existing_nullable=False)
    op.alter_column('chapters', 'title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment='Chapter title',
               existing_nullable=False)
    op.alter_column('chapters', 'content',
               existing_type=mysql.LONGTEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.Text(),
               existing_comment='Full chapter text',
               existing_nullable=True)
    op.alter_column('chapters', 'word_count',
               existing_type=mysql.INTEGER(),
               server_default=None,
               nullable=False,
               comment='Actual word count')
    op.alter_column('chapters', 'target_word_count',
               existing_type=mysql.INTEGER(),
               server_default=None,
               nullable=False,
               comment='Target word count')
    op.alter_column('chapters', 'status',
               existing_type=mysql.ENUM('planned', 'in_progress', 'completed', 'revised', collation='utf8mb4_unicode_ci'),
               server_default=None,
               nullable=False,
               comment='Chapter status')
    op.alter_column('chapters', 'id',
               existing_type=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               type_=sa.String(length=36),
               comment='UUID primary key',
               existing_comment='UUID',
               existing_nullable=False)
    op.alter_column('chapters', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(),
               nullable=False,
               comment='Record creation timestamp')
    op.alter_column('chapters', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(),
               nullable=False,
               comment='Record last update timestamp')
    op.drop_index(op.f('idx_chapter_number'), table_name='chapters')
    op.drop_index(op.f('idx_status'), table_name='chapters')
    op.drop_index(op.f('unique_chapter'), table_name='chapters')
    op.create_index(op.f('ix_chapters_chapter_number'), 'chapters', ['chapter_number'], unique=False)
    op.create_index(op.f('ix_chapters_status'), 'chapters', ['status'], unique=False)
    op.create_index(op.f('ix_chapters_story_bible_id'), 'chapters', ['story_bible_id'], unique=False)
    op.drop_table_comment(
        'chapters',
        existing_comment='Chapter content and metadata',
        schema=None
    )
    op.add_column('checkpoints', sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Record last update timestamp'))
    op.alter_column('checkpoints', 'project_id',
               existing_type=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               type_=sa.String(length=36),
               comment='Project ID',
               existing_nullable=False)
    op.alter_column('checkpoints', 'story_bible_id',
               existing_type=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               type_=sa.String(length=36),
               comment='Story Bible ID',
               existing_nullable=False)
    op.alter_column('checkpoints', 'checkpoint_type',
               existing_type=mysql.ENUM('concept', 'characters', 'outline', 'chapter', 'final', collation='utf8mb4_unicode_ci'),
               comment='Type of checkpoint',
               existing_nullable=False)
    op.alter_column('checkpoints', 'status',
               existing_type=mysql.ENUM('pending', 'approved', 'rejected', 'skipped', collation='utf8mb4_unicode_ci'),
               server_default=None,
               nullable=False,
               comment='Checkpoint status')
    op.alter_column('checkpoints', 'user_feedback',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='User feedback on checkpoint',
               existing_nullable=True)
    op.alter_column('checkpoints', 'rejection_reason',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Reason for rejection',
               existing_nullable=True)
    op.alter_column('checkpoints', 'reviewed_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_comment='When user reviewed checkpoint',
               existing_nullable=True)
    op.alter_column('checkpoints', 'id',
               existing_type=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               type_=sa.String(length=36),
               comment='UUID primary key',
               existing_comment='UUID',
               existing_nullable=False)
    op.alter_column('checkpoints', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(),
               nullable=False,
               comment='Record creation timestamp')
    op.drop_index(op.f('idx_created_at'), table_name='checkpoints')
    op.drop_index(op.f('idx_project_status'), table_name='checkpoints')
    op.drop_index(op.f('idx_type'), table_name='checkpoints')
    op.create_index(op.f('ix_checkpoints_checkpoint_type'), 'checkpoints', ['checkpoint_type'], unique=False)
    op.create_index(op.f('ix_checkpoints_project_id'), 'checkpoints', ['project_id'], unique=False)
    op.create_index(op.f('ix_checkpoints_status'), 'checkpoints', ['status'], unique=False)
    op.create_index(op.f('ix_checkpoints_story_bible_id'), 'checkpoints', ['story_bible_id'], unique=False)
    op.drop_table_comment(
        'checkpoints',
        existing_comment='Workflow checkpoints for user review',
        schema=None
    )
    op.add_column('images', sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Record last update timestamp'))
    op.alter_column('images', 'project_id',
               existing_type=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               type_=sa.String(length=36),
               comment='Project ID',
               existing_nullable=False)
    op.alter_column('images', 'story_bible_id',
               existing_type=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               type_=sa.String(length=36),
               comment='Story Bible ID',
               existing_nullable=False)
    op.alter_column('images', 'image_type',
               existing_type=mysql.ENUM('cover_art', 'character_portrait', 'scene_illustration', collation='utf8mb4_unicode_ci'),
               comment='Type of image',
               existing_nullable=False)
    op.alter_column('images', 'width',
               existing_type=mysql.INTEGER(),
               comment='Image width in pixels',
               existing_nullable=False)
    op.alter_column('images', 'height',
               existing_type=mysql.INTEGER(),
               comment='Image height in pixels',
               existing_nullable=False)
    op.alter_column('images', 'generation_cost',
               existing_type=mysql.DECIMAL(precision=10, scale=4),
               server_default=None,
               nullable=False,
               existing_comment='Cost in USD')
    op.alter_column('images', 'id',
               existing_type=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               type_=sa.String(length=36),
               comment='UUID primary key',
               existing_comment='UUID',
               existing_nullable=False)
    op.alter_column('images', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(),
               nullable=False,
               comment='Record creation timestamp')
    op.drop_index(op.f('idx_chapter'), table_name='images')
    op.drop_index(op.f('idx_character'), table_name='images')
    op.drop_index(op.f('idx_project_type'), table_name='images')
    op.create_index(op.f('ix_images_chapter_number'), 'images', ['chapter_number'], unique=False)
    op.create_index(op.f('ix_images_character_name'), 'images', ['character_name'], unique=False)
    op.create_index(op.f('ix_images_image_type'), 'images', ['image_type'], unique=False)
    op.create_index(op.f('ix_images_project_id'), 'images', ['project_id'], unique=False)
    op.create_index(op.f('ix_images_story_bible_id'), 'images', ['story_bible_id'], unique=False)
    op.drop_table_comment(
        'images',
        existing_comment='Generated image metadata',
        schema=None
    )
    op.alter_column('projects', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment='Project name',
               existing_nullable=False)
    op.alter_column('projects', 'description',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Project description',
               existing_nullable=True)
    op.alter_column('projects', 'genre',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='Book genre (e.g., Fantasy, Sci-Fi)',
               existing_nullable=True)
    op.alter_column('projects', 'target_length',
               existing_type=mysql.INTEGER(),
               server_default=None,
               nullable=False,
               existing_comment='Target word count')
    op.alter_column('projects', 'status',
               existing_type=mysql.ENUM('draft', 'in_progress', 'paused', 'completed', 'archived', collation='utf8mb4_unicode_ci'),
               server_default=None,
               nullable=False,
               comment='Project status')
    op.alter_column('projects', 'id',
               existing_type=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               type_=sa.String(length=36),
               comment='UUID primary key',
               existing_comment='UUID',
               existing_nullable=False)
    op.alter_column('projects', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(),
               nullable=False,
               comment='Record creation timestamp')
    op.alter_column('projects', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(),
               nullable=False,
               comment='Record last update timestamp')
    op.alter_column('projects', 'deleted_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_comment='Soft delete timestamp',
               existing_nullable=True)
    op.drop_index(op.f('idx_created_at'), table_name='projects')
    op.drop_index(op.f('idx_deleted_at'), table_name='projects')
    op.drop_index(op.f('idx_status'), table_name='projects')
    op.drop_table_comment(
        'projects',
        existing_comment='Project metadata and configuration',
        schema=None
    )
    op.add_column('story_bibles', sa.Column('additional_metadata', sa.JSON(), nullable=True, comment='Additional metadata'))
    op.alter_column('story_bibles', 'project_id',
               existing_type=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               type_=sa.String(length=36),
               comment='Project ID',
               existing_nullable=False)
    op.alter_column('story_bibles', 'version',
               existing_type=mysql.INTEGER(),
               server_default=None,
               existing_comment='Version number for rollback',
               existing_nullable=False)
    op.alter_column('story_bibles', 'id',
               existing_type=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               type_=sa.String(length=36),
               comment='UUID primary key',
               existing_comment='UUID',
               existing_nullable=False)
    op.alter_column('story_bibles', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(),
               nullable=False,
               comment='Record creation timestamp')
    op.alter_column('story_bibles', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(),
               nullable=False,
               comment='Record last update timestamp')
    op.drop_index(op.f('idx_project_version'), table_name='story_bibles')
    op.drop_index(op.f('idx_updated_at'), table_name='story_bibles')
    op.create_index(op.f('ix_story_bibles_project_id'), 'story_bibles', ['project_id'], unique=False)
    op.drop_table_comment(
        'story_bibles',
        existing_comment='Story Bible state with versioning',
        schema=None
    )
    op.drop_column('story_bibles', 'metadata')
    op.add_column('workflow_states', sa.Column('created_at', sa.DateTime(), nullable=False, comment='Record creation timestamp'))
    op.add_column('workflow_states', sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Record last update timestamp'))
    op.alter_column('workflow_states', 'project_id',
               existing_type=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               type_=sa.String(length=36),
               comment='Project ID',
               existing_nullable=False)
    op.alter_column('workflow_states', 'status',
               existing_type=mysql.ENUM('running', 'paused', 'completed', 'failed', 'cancelled', collation='utf8mb4_unicode_ci'),
               server_default=None,
               nullable=False,
               comment='Workflow status')
    op.alter_column('workflow_states', 'completed_steps',
               existing_type=mysql.INTEGER(),
               server_default=None,
               nullable=False,
               comment='Completed steps')
    op.alter_column('workflow_states', 'progress_percentage',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               server_default=None,
               nullable=False,
               comment='Progress percentage (0-100)')
    op.alter_column('workflow_states', 'error_message',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Error message if failed',
               existing_nullable=True)
    op.alter_column('workflow_states', 'error_stack',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Error stack trace',
               existing_nullable=True)
    op.alter_column('workflow_states', 'started_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(),
               nullable=False,
               comment='Workflow start time')
    op.alter_column('workflow_states', 'paused_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               comment='When workflow was paused',
               existing_nullable=True)
    op.alter_column('workflow_states', 'resumed_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               comment='When workflow was resumed',
               existing_nullable=True)
    op.alter_column('workflow_states', 'completed_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               comment='When workflow completed',
               existing_nullable=True)
    op.alter_column('workflow_states', 'id',
               existing_type=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               type_=sa.String(length=36),
               comment='UUID primary key',
               existing_comment='UUID',
               existing_nullable=False)
    op.drop_index(op.f('idx_project_status'), table_name='workflow_states')
    op.drop_index(op.f('idx_started_at'), table_name='workflow_states')
    op.create_index(op.f('ix_workflow_states_project_id'), 'workflow_states', ['project_id'], unique=False)
    op.create_index(op.f('ix_workflow_states_started_at'), 'workflow_states', ['started_at'], unique=False)
    op.create_index(op.f('ix_workflow_states_status'), 'workflow_states', ['status'], unique=False)
    op.drop_table_comment(
        'workflow_states',
        existing_comment='Workflow execution state',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'workflow_states',
        'Workflow execution state',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_workflow_states_status'), table_name='workflow_states')
    op.drop_index(op.f('ix_workflow_states_started_at'), table_name='workflow_states')
    op.drop_index(op.f('ix_workflow_states_project_id'), table_name='workflow_states')
    op.create_index(op.f('idx_started_at'), 'workflow_states', ['started_at'], unique=False)
    op.create_index(op.f('idx_project_status'), 'workflow_states', ['project_id', 'status'], unique=False)
    op.alter_column('workflow_states', 'id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               comment='UUID',
               existing_comment='UUID primary key',
               existing_nullable=False)
    op.alter_column('workflow_states', 'completed_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               comment=None,
               existing_comment='When workflow completed',
               existing_nullable=True)
    op.alter_column('workflow_states', 'resumed_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               comment=None,
               existing_comment='When workflow was resumed',
               existing_nullable=True)
    op.alter_column('workflow_states', 'paused_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               comment=None,
               existing_comment='When workflow was paused',
               existing_nullable=True)
    op.alter_column('workflow_states', 'started_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=mysql.TIMESTAMP(),
               nullable=True,
               comment=None,
               existing_comment='Workflow start time')
    op.alter_column('workflow_states', 'error_stack',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Error stack trace',
               existing_nullable=True)
    op.alter_column('workflow_states', 'error_message',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Error message if failed',
               existing_nullable=True)
    op.alter_column('workflow_states', 'progress_percentage',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               server_default=sa.text("'0.00'"),
               nullable=True,
               comment=None,
               existing_comment='Progress percentage (0-100)')
    op.alter_column('workflow_states', 'completed_steps',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'0'"),
               nullable=True,
               comment=None,
               existing_comment='Completed steps')
    op.alter_column('workflow_states', 'status',
               existing_type=mysql.ENUM('running', 'paused', 'completed', 'failed', 'cancelled', collation='utf8mb4_unicode_ci'),
               server_default=sa.text("'running'"),
               nullable=True,
               comment=None,
               existing_comment='Workflow status')
    op.alter_column('workflow_states', 'project_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               comment=None,
               existing_comment='Project ID',
               existing_nullable=False)
    op.drop_column('workflow_states', 'updated_at')
    op.drop_column('workflow_states', 'created_at')
    op.add_column('story_bibles', sa.Column('metadata', mysql.JSON(), nullable=True, comment='Additional metadata'))
    op.create_table_comment(
        'story_bibles',
        'Story Bible state with versioning',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_story_bibles_project_id'), table_name='story_bibles')
    op.create_index(op.f('idx_updated_at'), 'story_bibles', ['updated_at'], unique=False)
    op.create_index(op.f('idx_project_version'), 'story_bibles', ['project_id', 'version'], unique=False)
    op.alter_column('story_bibles', 'updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
               type_=mysql.TIMESTAMP(),
               nullable=True,
               comment=None,
               existing_comment='Record last update timestamp')
    op.alter_column('story_bibles', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=mysql.TIMESTAMP(),
               nullable=True,
               comment=None,
               existing_comment='Record creation timestamp')
    op.alter_column('story_bibles', 'id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               comment='UUID',
               existing_comment='UUID primary key',
               existing_nullable=False)
    op.alter_column('story_bibles', 'version',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'1'"),
               existing_comment='Version number for rollback',
               existing_nullable=False)
    op.alter_column('story_bibles', 'project_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               comment=None,
               existing_comment='Project ID',
               existing_nullable=False)
    op.drop_column('story_bibles', 'additional_metadata')
    op.create_table_comment(
        'projects',
        'Project metadata and configuration',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_status'), 'projects', ['status'], unique=False)
    op.create_index(op.f('idx_deleted_at'), 'projects', ['deleted_at'], unique=False)
    op.create_index(op.f('idx_created_at'), 'projects', ['created_at'], unique=False)
    op.alter_column('projects', 'deleted_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_comment='Soft delete timestamp',
               existing_nullable=True)
    op.alter_column('projects', 'updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
               type_=mysql.TIMESTAMP(),
               nullable=True,
               comment=None,
               existing_comment='Record last update timestamp')
    op.alter_column('projects', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=mysql.TIMESTAMP(),
               nullable=True,
               comment=None,
               existing_comment='Record creation timestamp')
    op.alter_column('projects', 'id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               comment='UUID',
               existing_comment='UUID primary key',
               existing_nullable=False)
    op.alter_column('projects', 'status',
               existing_type=mysql.ENUM('draft', 'in_progress', 'paused', 'completed', 'archived', collation='utf8mb4_unicode_ci'),
               server_default=sa.text("'draft'"),
               nullable=True,
               comment=None,
               existing_comment='Project status')
    op.alter_column('projects', 'target_length',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'80000'"),
               nullable=True,
               existing_comment='Target word count')
    op.alter_column('projects', 'genre',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment=None,
               existing_comment='Book genre (e.g., Fantasy, Sci-Fi)',
               existing_nullable=True)
    op.alter_column('projects', 'description',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Project description',
               existing_nullable=True)
    op.alter_column('projects', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment=None,
               existing_comment='Project name',
               existing_nullable=False)
    op.create_table_comment(
        'images',
        'Generated image metadata',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_images_story_bible_id'), table_name='images')
    op.drop_index(op.f('ix_images_project_id'), table_name='images')
    op.drop_index(op.f('ix_images_image_type'), table_name='images')
    op.drop_index(op.f('ix_images_character_name'), table_name='images')
    op.drop_index(op.f('ix_images_chapter_number'), table_name='images')
    op.create_index(op.f('idx_project_type'), 'images', ['project_id', 'image_type'], unique=False)
    op.create_index(op.f('idx_character'), 'images', ['character_name'], unique=False)
    op.create_index(op.f('idx_chapter'), 'images', ['chapter_number'], unique=False)
    op.alter_column('images', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=mysql.TIMESTAMP(),
               nullable=True,
               comment=None,
               existing_comment='Record creation timestamp')
    op.alter_column('images', 'id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               comment='UUID',
               existing_comment='UUID primary key',
               existing_nullable=False)
    op.alter_column('images', 'generation_cost',
               existing_type=mysql.DECIMAL(precision=10, scale=4),
               server_default=sa.text("'0.0000'"),
               nullable=True,
               existing_comment='Cost in USD')
    op.alter_column('images', 'height',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Image height in pixels',
               existing_nullable=False)
    op.alter_column('images', 'width',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Image width in pixels',
               existing_nullable=False)
    op.alter_column('images', 'image_type',
               existing_type=mysql.ENUM('cover_art', 'character_portrait', 'scene_illustration', collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Type of image',
               existing_nullable=False)
    op.alter_column('images', 'story_bible_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               comment=None,
               existing_comment='Story Bible ID',
               existing_nullable=False)
    op.alter_column('images', 'project_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               comment=None,
               existing_comment='Project ID',
               existing_nullable=False)
    op.drop_column('images', 'updated_at')
    op.create_table_comment(
        'checkpoints',
        'Workflow checkpoints for user review',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_checkpoints_story_bible_id'), table_name='checkpoints')
    op.drop_index(op.f('ix_checkpoints_status'), table_name='checkpoints')
    op.drop_index(op.f('ix_checkpoints_project_id'), table_name='checkpoints')
    op.drop_index(op.f('ix_checkpoints_checkpoint_type'), table_name='checkpoints')
    op.create_index(op.f('idx_type'), 'checkpoints', ['checkpoint_type'], unique=False)
    op.create_index(op.f('idx_project_status'), 'checkpoints', ['project_id', 'status'], unique=False)
    op.create_index(op.f('idx_created_at'), 'checkpoints', ['created_at'], unique=False)
    op.alter_column('checkpoints', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=mysql.TIMESTAMP(),
               nullable=True,
               comment=None,
               existing_comment='Record creation timestamp')
    op.alter_column('checkpoints', 'id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               comment='UUID',
               existing_comment='UUID primary key',
               existing_nullable=False)
    op.alter_column('checkpoints', 'reviewed_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_comment='When user reviewed checkpoint',
               existing_nullable=True)
    op.alter_column('checkpoints', 'rejection_reason',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Reason for rejection',
               existing_nullable=True)
    op.alter_column('checkpoints', 'user_feedback',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='User feedback on checkpoint',
               existing_nullable=True)
    op.alter_column('checkpoints', 'status',
               existing_type=mysql.ENUM('pending', 'approved', 'rejected', 'skipped', collation='utf8mb4_unicode_ci'),
               server_default=sa.text("'pending'"),
               nullable=True,
               comment=None,
               existing_comment='Checkpoint status')
    op.alter_column('checkpoints', 'checkpoint_type',
               existing_type=mysql.ENUM('concept', 'characters', 'outline', 'chapter', 'final', collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Type of checkpoint',
               existing_nullable=False)
    op.alter_column('checkpoints', 'story_bible_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               comment=None,
               existing_comment='Story Bible ID',
               existing_nullable=False)
    op.alter_column('checkpoints', 'project_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               comment=None,
               existing_comment='Project ID',
               existing_nullable=False)
    op.drop_column('checkpoints', 'updated_at')
    op.create_table_comment(
        'chapters',
        'Chapter content and metadata',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_chapters_story_bible_id'), table_name='chapters')
    op.drop_index(op.f('ix_chapters_status'), table_name='chapters')
    op.drop_index(op.f('ix_chapters_chapter_number'), table_name='chapters')
    op.create_index(op.f('unique_chapter'), 'chapters', ['story_bible_id', 'chapter_number'], unique=True)
    op.create_index(op.f('idx_status'), 'chapters', ['status'], unique=False)
    op.create_index(op.f('idx_chapter_number'), 'chapters', ['chapter_number'], unique=False)
    op.alter_column('chapters', 'updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
               type_=mysql.TIMESTAMP(),
               nullable=True,
               comment=None,
               existing_comment='Record last update timestamp')
    op.alter_column('chapters', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=mysql.TIMESTAMP(),
               nullable=True,
               comment=None,
               existing_comment='Record creation timestamp')
    op.alter_column('chapters', 'id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               comment='UUID',
               existing_comment='UUID primary key',
               existing_nullable=False)
    op.alter_column('chapters', 'status',
               existing_type=mysql.ENUM('planned', 'in_progress', 'completed', 'revised', collation='utf8mb4_unicode_ci'),
               server_default=sa.text("'planned'"),
               nullable=True,
               comment=None,
               existing_comment='Chapter status')
    op.alter_column('chapters', 'target_word_count',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'3000'"),
               nullable=True,
               comment=None,
               existing_comment='Target word count')
    op.alter_column('chapters', 'word_count',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'0'"),
               nullable=True,
               comment=None,
               existing_comment='Actual word count')
    op.alter_column('chapters', 'content',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(collation='utf8mb4_unicode_ci'),
               existing_comment='Full chapter text',
               existing_nullable=True)
    op.alter_column('chapters', 'title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment=None,
               existing_comment='Chapter title',
               existing_nullable=False)
    op.alter_column('chapters', 'chapter_number',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Chapter number (1-based)',
               existing_nullable=False)
    op.alter_column('chapters', 'story_bible_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               comment=None,
               existing_comment='Story Bible ID',
               existing_nullable=False)
    op.create_table_comment(
        'api_costs',
        'API usage and cost tracking',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_api_costs_provider'), table_name='api_costs')
    op.drop_index(op.f('ix_api_costs_project_id'), table_name='api_costs')
    op.drop_index(op.f('ix_api_costs_api_type'), table_name='api_costs')
    op.create_index(op.f('idx_project_provider'), 'api_costs', ['project_id', 'provider'], unique=False)
    op.create_index(op.f('idx_created_at'), 'api_costs', ['created_at'], unique=False)
    op.create_index(op.f('idx_api_type'), 'api_costs', ['api_type'], unique=False)
    op.alter_column('api_costs', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=mysql.TIMESTAMP(),
               nullable=True,
               comment=None,
               existing_comment='Record creation timestamp')
    op.alter_column('api_costs', 'id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               comment='UUID',
               existing_comment='UUID primary key',
               existing_nullable=False)
    op.alter_column('api_costs', 'error_message',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Error message if failed',
               existing_nullable=True)
    op.alter_column('api_costs', 'success',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               nullable=True,
               comment=None,
               existing_comment='Whether request succeeded')
    op.alter_column('api_costs', 'api_type',
               existing_type=mysql.ENUM('text', 'image', collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='API type',
               existing_nullable=False)
    op.alter_column('api_costs', 'provider',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='mistral, openai',
               existing_comment='AI provider (mistral, openai)',
               existing_nullable=False)
    op.alter_column('api_costs', 'project_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               comment=None,
               existing_comment='Project ID',
               existing_nullable=False)
    op.drop_column('api_costs', 'updated_at')
    op.create_table_comment(
        'agent_deltas',
        'Agent change audit trail',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_agent_deltas_story_bible_id'), table_name='agent_deltas')
    op.drop_index(op.f('ix_agent_deltas_agent_name'), table_name='agent_deltas')
    op.create_index(op.f('idx_story_bible'), 'agent_deltas', ['story_bible_id'], unique=False)
    op.create_index(op.f('idx_created_at'), 'agent_deltas', ['created_at'], unique=False)
    op.create_index(op.f('idx_agent'), 'agent_deltas', ['agent_name'], unique=False)
    op.alter_column('agent_deltas', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=mysql.TIMESTAMP(),
               nullable=True,
               comment=None,
               existing_comment='Record creation timestamp')
    op.alter_column('agent_deltas', 'id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               comment='UUID',
               existing_comment='UUID primary key',
               existing_nullable=False)
    op.alter_column('agent_deltas', 'cost',
               existing_type=mysql.DECIMAL(precision=10, scale=4),
               server_default=sa.text("'0.0000'"),
               nullable=True,
               existing_comment='Cost in USD')
    op.alter_column('agent_deltas', 'execution_time_ms',
               existing_type=mysql.INTEGER(),
               comment='Agent execution time',
               existing_comment='Agent execution time in milliseconds',
               existing_nullable=True)
    op.alter_column('agent_deltas', 'agent_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment=None,
               existing_comment='Agent name',
               existing_nullable=False)
    op.alter_column('agent_deltas', 'story_bible_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               comment=None,
               existing_comment='Story Bible ID',
               existing_nullable=False)
    op.drop_column('agent_deltas', 'updated_at')
    op.create_table('schema_version',
    sa.Column('version', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('applied_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('description', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.PrimaryKeyConstraint('version'),
    comment='Schema version tracking',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='Schema version tracking',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
